permalink: /:title/

paginate:          10
paginate_path:     "/podcasts/:num/"
excerpt_separator: "<!--more-->"
url:               "https://threedevsandamaybe.com"
podcasts:          "https://podcasts.threedevsandamaybe.com"
podtrac:           "https://www.podtrac.com/pts/redirect.mp3/podcasts.threedevsandamaybe.com"
timezone:          "Europe/London"

sass:
  sass_dir: _sass
  style:    :compressed

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
