permalink: /:title/

paginate:          10
paginate_path:     "/podcasts/:num/"
excerpt_separator: "<!--more-->"
url:               "http://threedevsandamaybe.com"
podcasts:          "http://podcasts.threedevsandamaybe.com"
podtrac:           "http://www.podtrac.com/pts/redirect.mp3/podcasts.threedevsandamaybe.com"
timezone:          "Europe/London"

sass:
  sass_dir: _sass
  style:    :compressed

gems:
  - jekyll-redirect-from
